require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SchemeApproversController do

  # This should return the minimal set of attributes required to create a valid
  # SchemeApprover. As you add validations to SchemeApprover, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "approver_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SchemeApproversController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all scheme_approvers as @scheme_approvers" do
      scheme_approver = SchemeApprover.create! valid_attributes
      get :index, {}, valid_session
      assigns(:scheme_approvers).should eq([scheme_approver])
    end
  end

  describe "GET show" do
    it "assigns the requested scheme_approver as @scheme_approver" do
      scheme_approver = SchemeApprover.create! valid_attributes
      get :show, {:id => scheme_approver.to_param}, valid_session
      assigns(:scheme_approver).should eq(scheme_approver)
    end
  end

  describe "GET new" do
    it "assigns a new scheme_approver as @scheme_approver" do
      get :new, {}, valid_session
      assigns(:scheme_approver).should be_a_new(SchemeApprover)
    end
  end

  describe "GET edit" do
    it "assigns the requested scheme_approver as @scheme_approver" do
      scheme_approver = SchemeApprover.create! valid_attributes
      get :edit, {:id => scheme_approver.to_param}, valid_session
      assigns(:scheme_approver).should eq(scheme_approver)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SchemeApprover" do
        expect {
          post :create, {:scheme_approver => valid_attributes}, valid_session
        }.to change(SchemeApprover, :count).by(1)
      end

      it "assigns a newly created scheme_approver as @scheme_approver" do
        post :create, {:scheme_approver => valid_attributes}, valid_session
        assigns(:scheme_approver).should be_a(SchemeApprover)
        assigns(:scheme_approver).should be_persisted
      end

      it "redirects to the created scheme_approver" do
        post :create, {:scheme_approver => valid_attributes}, valid_session
        response.should redirect_to(SchemeApprover.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved scheme_approver as @scheme_approver" do
        # Trigger the behavior that occurs when invalid params are submitted
        SchemeApprover.any_instance.stub(:save).and_return(false)
        post :create, {:scheme_approver => { "approver_id" => "invalid value" }}, valid_session
        assigns(:scheme_approver).should be_a_new(SchemeApprover)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SchemeApprover.any_instance.stub(:save).and_return(false)
        post :create, {:scheme_approver => { "approver_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested scheme_approver" do
        scheme_approver = SchemeApprover.create! valid_attributes
        # Assuming there are no other scheme_approvers in the database, this
        # specifies that the SchemeApprover created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SchemeApprover.any_instance.should_receive(:update_attributes).with({ "approver_id" => "1" })
        put :update, {:id => scheme_approver.to_param, :scheme_approver => { "approver_id" => "1" }}, valid_session
      end

      it "assigns the requested scheme_approver as @scheme_approver" do
        scheme_approver = SchemeApprover.create! valid_attributes
        put :update, {:id => scheme_approver.to_param, :scheme_approver => valid_attributes}, valid_session
        assigns(:scheme_approver).should eq(scheme_approver)
      end

      it "redirects to the scheme_approver" do
        scheme_approver = SchemeApprover.create! valid_attributes
        put :update, {:id => scheme_approver.to_param, :scheme_approver => valid_attributes}, valid_session
        response.should redirect_to(scheme_approver)
      end
    end

    describe "with invalid params" do
      it "assigns the scheme_approver as @scheme_approver" do
        scheme_approver = SchemeApprover.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SchemeApprover.any_instance.stub(:save).and_return(false)
        put :update, {:id => scheme_approver.to_param, :scheme_approver => { "approver_id" => "invalid value" }}, valid_session
        assigns(:scheme_approver).should eq(scheme_approver)
      end

      it "re-renders the 'edit' template" do
        scheme_approver = SchemeApprover.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SchemeApprover.any_instance.stub(:save).and_return(false)
        put :update, {:id => scheme_approver.to_param, :scheme_approver => { "approver_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested scheme_approver" do
      scheme_approver = SchemeApprover.create! valid_attributes
      expect {
        delete :destroy, {:id => scheme_approver.to_param}, valid_session
      }.to change(SchemeApprover, :count).by(-1)
    end

    it "redirects to the scheme_approvers list" do
      scheme_approver = SchemeApprover.create! valid_attributes
      delete :destroy, {:id => scheme_approver.to_param}, valid_session
      response.should redirect_to(scheme_approvers_url)
    end
  end

end
